# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'fb03' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'RSKImageCropper','2.1.0'
  pod 'QBImagePickerController', '3.4.0'

end
target 'fb03-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
end

target 'fb03Tests' do
    inherit! :search_paths
    # Pods for testing
end

